server:
  port: 9000

spring:
  application:
    name: service-product
  cloud:
    nacos:
      discovery:
        server-addr: 172.31.16.64:8848
      server-addr: 172.31.16.64:8848
      config:
        import-check:
          enabled: false